### ISSUE TITLE
Le plugin est-il compatible avec un Wordpress Multi-site ?

### ISSUE THREAD

**Issue by bigbang-marc** [OpenAgenda/wordpress#14]
Tout est dans le titre : je souhaiterais savoir si l'extension OpenAgenda Wordpress a déjà été testée sur un Wordpress Multisite et si elle est bien compatible avec ce mode de fonctionnement ?
D'avance merci pour votre retour, qui conditionnera un choix technique pour un projet.

**Comment by vincedubroeucq** [comment]
Bonjour,
Oui, le plugin fonctionne sur un multisite, pas de souci !
