### ISSUE TITLE
Désolé aucun événement

### ISSUE THREAD

**Issue by operrot** [OpenAgenda/wordpress#17]
L'extension marchait jusqu'à une mise à jour. Depuis quelques temps malgré plusieurs tentatives de désinstallation, réinstallation, en vidant ou pas les réglages, regénération de la clé API, recréation de l'agenda, j'ai toujours un message "Aucun événement trouvé".
UID : 89317407
![ScreenHunter 2871](https://user-images.githubusercontent.com/32200460/211184938-caa86f04-a8a6-4992-b2e3-3c43b080cc05.jpg)

**Comment by kaore** [comment]
Bonjour @operrot je vous contacte par email pour avoir plus d'informations sur votre agenda.
