### ISSUE TITLE
Active filters on top of the list in default templates

### ISSUE THREAD

**Issue by kaore** [OpenAgenda/wordpress#2]
The active filters (widget/filter script) summarizes the state of activated filters. In most cases, users expect to see it above the event list together with the total of matching events and eventual pagination information.

It would be better to have it displayed this way on the default layout.

**Comment by vincedubroeucq** [comment]
I understand.
A template modification has been done, to add a list header on event list pages. 
The template contains a simple event count, and the active filter widget.
The event count is also dynamically refreshed when the event list is refreshed.
