### ISSUE TITLE
Upload du fichier filters.js non minimifié (/assets/js/filters.js)

### ISSUE THREAD

**Issue by dcr31000** [OpenAgenda/wordpress#22]
Bonjour,

Je souhaite personnaliser l'affichage des filtres sur mon Open Agenda. J'ai remarqué que c'est le fichier filters.min.js qui est responsable de la structure HTML des filtres.
Je souhaite surcharger les méthodes des rendus des filtres afin d'en modifier la structure et l'affichage. Cependant, je vois que vous avez uplodé sur ce repo uniquement la version minimifiée (alors que les autres fichiers .js sont disponibles en entier).

Est-ce possible, s'il vous plait, d'envoyer sur ce repo le fichier filters.js ?

Merci

**Comment by vincedubroeucq** [comment]
Bonjour,
Désolé pour la réponse tardive.

Les filtres utilisés sont issus d'un package que vous pouvez trouver ici : [https://www.npmjs.com/package/@openagenda/react-filters](https://www.npmjs.com/package/@openagenda/react-filters
)

Le dépôt Git correspondant est ici : [https://github.com/OpenAgenda/oa-public/tree/main/react-filters](https://github.com/OpenAgenda/oa-public/tree/main/react-filters)

Vous aurez besoin d'installer le tout et de recompiler vous-même le fichier, par contre.

Ensuite, dans le plugin WordPress, je vous recommande de ne pas modifier le fichier fourni, sinon vous allez perdre vos modifications à la prochaine mise à jour.
Dé-enregistrez le script des filtres à l'aide de `wp_dequeue_script()` ou `wp_deregister_script()`, et chargez le votre à la place, que vous aurez mis dans une petite extension ou votre thème enfant.

J'espère que cela répond à votre question !
