### ISSUE TITLE
Filtres à valeurs multiples

### ISSUE THREAD

**Issue by gaetleba** [OpenAgenda/wordpress#23]
L'utilisation de plusieurs valeurs sur un même filtre semble ne prendre en compte que la dernière valeur.
Par exemple 
```
[openagenda_filter_preview uid=******** size=25 filters=?q.relative=upcoming&q.relative=current ]
``` 
affiche uniquement les évènements en cours et pas ceux à venir.
Est-ce que j'ai fait une erreur de config ?

**Comment by vincedubroeucq** [comment]
Bonjour,
Le filtre `relative` demande un tableau.

```
[openagenda_filter_preview uid=******** size=25 filters=?q.relative[]=upcoming&q.relative[]=current ]
```
ou
```
[openagenda_filter_preview uid=******** size=25 filters=?q.relative[0]=upcoming&q.relative[1]=current ]
```

devrait fonctionner.

J'espère vous avoir aidé !

**Comment by gaetleba** [comment]
Malheureusement l'utilisation des crochets dans ce contexte pose problème et semble clore trop tôt la définition du shortcode wordpress.

**Comment by vincedubroeucq** [comment]
Ah oui, c'est vrai. Désolé !
Essayez d'url-encoder la valeur du paramètre : 

```
[openagenda_filter_preview uid="..." size="25" filters="?q.relative%5B%5D%3Dupcoming%26q.relative%5B%5D%3Dcurrent"]
```

**Comment by gaetleba** [comment]
Ça fonctionne. Merci !

**Comment by vincedubroeucq** [comment]
Super !
