### ISSUE TITLE
WP Shortcode filter for categories not working

### ISSUE THREAD

**Issue by danana** [OpenAgenda/wordpress#27]
I am using the shortcode: [openagenda_filter_choice additional_field="test-champ-categories-differentes”] in the WP plugin but nothing shows up. 
I was able to add the map, calendar, search and keywords filter, but I am not able to bring in the categories. I tried using the parameter “field" and “additional_field" with no success. Can you help me with a piece of advice on how to do this? 

![coolturalia-wp](https://github.com/OpenAgenda/wordpress/assets/2064175/c029d075-ff03-468d-8aec-1cf4af00c138)

https://openagenda.com/coolturaliatest - UID: 95186839
My events categories are coming in this json: "test-field-categories-different” 

![coolturalia2](https://github.com/OpenAgenda/wordpress/assets/2064175/78faaf87-4e2e-4d3a-8056-9592d25e0067)

Thank you!

**Comment by vincedubroeucq** [comment]
Hello,
The `additional_field` parameters only works when the `field` is set to `additional_field`.
Try : 
```
[openagenda_filter_choice field="additional_field" additional_field="test-champ-categories-differentes"]
```

That should work.
Hope that helps !
