### ISSUE TITLE
[bug] Erreur avec les évènements en Ligne

### ISSUE THREAD

**Issue by charlie-toyab** [OpenAgenda/wordpress#3]
Lorsqu'un évènement n'a pas de lieu, j'ai une erreur PHP.
C'est le cas lorsque l'évènements est un évènement "en ligne" par exemple

[lien test](http://lpa.bayot.org/agenda/le-joli-mois-de-leurope/la-pause-europeenne/?context=eyJsaW1pdCI6MTAsInBhZ2UiOjEsInRvdGFsIjo0NCwiZXZlbnRfb2Zmc2V0IjozfQ=)

`Warning: Illegal string offset 'access' in /home/customer/www/public_html/wp-content/plugins/openagenda/inc/template-tags.php on line 98`

**Comment by kaore** [comment]
C'est un changement sur la structure des événements qui n'est pas encore géré par le plugin. Ca demandera un évolutif: pouvoir définir une timezone par défaut

**Comment by vincedubroeucq** [comment]
J'ai ajouté une vérification du champ "attendanceMode" et de la présence d'un lieu avant d'appeler le template du lieu.
