### ISSUE TITLE
Ajout de boutons sur le filtre par date

### ISSUE THREAD

**Issue by ydufresne-alesagglo** [OpenAgenda/wordpress#37]
Bonjour,
Est il possible d'ajouter les boutons [Demain], [Ce week-end] et [Cette semaine] sous le sélecteur de date dans les filtres ?
Cordialement

**Comment by vincedubroeucq** [comment]
Bonjour,
Vous disposez d'un paramètre dans le widget filtre pour ce faire.
![image](https://github.com/OpenAgenda/wordpress/assets/31403596/33eb62ff-b939-40a6-b0fb-7523cf8d6d6a)
Cordialement

**Comment by ydufresne-alesagglo** [comment]
D'accord. Je n'avais pas fait le test avec une widget. J'utilise le shortcode [openagenda_filter_calendar] qui ne prend pas de paramètres.

**Comment by vincedubroeucq** [comment]
Pouvez-vous essayer le paramètre `display_ranges` sur 1  ?
 `[openagenda_filter_calendar defined_ranges="1"]`

**Comment by ydufresne-alesagglo** [comment]
cela a fonctionné avec le paramètre `display_ranges=1`, merci

**Comment by ydufresne-alesagglo** [comment]
ou avec le shortcode [openagenda_filter_ranges] (non documenté)

**Comment by vincedubroeucq** [comment]
Bonjour,
Oui, je n'ai pas encore mis à jour la documentation sur cette fonctionnalité de la dernière version. 
Désolé !
