### ISSUE TITLE
Format de date sur filtre Debut / Fin

### ISSUE THREAD

**Issue by ydufresne-alesagglo** [OpenAgenda/wordpress#39]
Bonjour,

Les dates de début et de fin sélectionnées pour filtrer les événements ne s'affichent pas avec le format sélectionné dans les réglages généraux de WordPress.

Cordialement

**Comment by vincedubroeucq** [comment]
Bonjour,
Vous parlez des dates dans le filtre calendrier ?

**Comment by ydufresne-alesagglo** [comment]
Les dates qui s'affichent dans les boutons debut / fin une fois qu'on a fait un filtrage sur les dates.

**Comment by kaore** [comment]
Bonjour,

Nous étudions un évolutif pour permettre cette fonction et vous ferons un retour ici sur le sujet.

Bonne journée

**Comment by ydufresne-alesagglo** [comment]
corrigé avec la version 2.11
