### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by sebastienserre** [OpenAgenda/wordpress#43]
Bonjour,

Connaissant l'appétence de @vincedubroeucq pour le block editor, je suis étonné de ne voir que des code courts.
Un développement de blocs pour remplacer les shortcode est il en cours ?

**Comment by vincedubroeucq** [comment]
Hello,
En cours non, mais sur une todo oui.
Etant donné que la majorité des utilisateurs n'utilisent pas le code court pour les événements, je ne pense pas qu'un bloc pour la grille des événements serait utile.
Par contre, pour les widgets filtres, oui.
C'est une idée au backlog donc.

**Comment by kaore** [comment]
Ce sujet rejoint la demande suivante: https://github.com/OpenAgenda/wordpress/issues/33

**Comment by timthee** [comment]
De mon côté je serais ravi de pouvoir gérer une liste d'événements à partir d'un bloc sur le modèle du bloc "query" de Wordpress, qui me permettrait en indiquant juste l'UUID de l'agenda et le nombre d'événements (avec la possibilité de décalage du premier éventuellement) de pouvoir construire la présentation d'une grille ou liste d'événements, par exemple... Et de pouvoir le faire différemment en fonction de la page où je veux l'utiliser
