### ISSUE TITLE
eventContainer is null

### ISSUE THREAD

**Issue by Latieulej** [OpenAgenda/wordpress#45]
Bonjour,

J'essaie de mettre en place OpenAgenda sur un site WordPress via le plugin. 
J'ai bien renseigné la clé API dans les réglages, ainsi que UID de l’agenda sur la page correspondante.

Le problème est qu'une fois sur la page en front, rien ne s'affiche et j'ai le message suivant dans la console : 

![image](https://github.com/OpenAgenda/wordpress/assets/23471572/1c2fcd81-6fea-451c-a87e-17bbff69185e)

J'ai testé avec et sans le shortcode dans le contenu, mais le soucis persiste.

Auriez-vous une idée du problème s'il vous plaît ?

**Comment by vincedubroeucq** [comment]
Bonjour,
Est-ce que je peux voir la page correspondante ?
Merci

**Comment by Latieulej** [comment]
Oui bien sûr, voici l'URL : https://preprod.castelnau-estretefonds.fr/calendar/evenements/

**Comment by vincedubroeucq** [comment]
Effectivement, le conteneur d'événements n'est pas injecté dans le contenu.
Pouvez-vous essayer de mettre le code court [openagenda] dans le contenu de la page agenda ?

**Comment by Latieulej** [comment]
En mettant le shortcode ainsi que du texte je me suis aperçue que cela ne fonctionnait pas, mais qu'en plus mon texte non plus ne s'affichait pas non plus. Ce qui m'a fait dire d'aller fouiller dans le thème, pour réaliser que the_content() n'était jamais appelé dans single.php ...

Problème résolu donc en ajoutant la fonction manquante à mon fichier ! 

Désolée pour le dérangement.

**Comment by vincedubroeucq** [comment]
Pas de souci !
