### ISSUE TITLE
Problème pour récupérer les datas des events dans le widget preview

### ISSUE THREAD

**Issue by maximedelamare** [OpenAgenda/wordpress#6]
Je voudrais afficher "En ligne " sur le widget de preview pour les evenements sans location. 
Le problème c'est que lorsque j'utilise:
            $latitude  = openagenda_get_field( 'location.latitude' ); 
            $longitude = openagenda_get_field( 'location.longitude' ); 
par exemple j'ai une erreur.
de type:
![1](https://user-images.githubusercontent.com/9953614/119111532-7127fd80-ba23-11eb-83e9-a93ad9f908c5.png)

et si j'ajoute l'uid de l'event j'ai une erreur similaire:
![2](https://user-images.githubusercontent.com/9953614/119111546-74bb8480-ba23-11eb-8e59-203cdba7a058.png)

**Comment by vincedubroeucq** [comment]
Le Widget de preview ne charge pas l'export JSON de l'agenda. En général, le widget est utilisé sur des pages qui ne sont pas des pages agenda.
Par conséquent, si on n'est pas sur une page Agenda, les fonctions openagenda_ de l'extension ne fonctionneront pas.
Donc en fait, l'erreur est normale ici : on tente d'accéder à la globale $openagenda pour lire des données d'événement, alors que celle-ci n'existe pas, et ne le sera que sur une page agenda.
Pour ajouter des données dans la preview, le template est un template JS Handlebar, qui est lu par le script controlleur JS principal. 
Malheureusement, les tags {location.longitude} et {location.latitude} ne sont pas reconnus.
