### ISSUE TITLE
Affichage des événements passés

### ISSUE THREAD

**Issue by romainlange** [OpenAgenda/wordpress#9]
L'agenda de Menton (https://openagenda.com/menton) est intégré ici : https://www.agenda-menton.fr/agenda/ville-de-menton/

Les liens pointant vers des événements passés n'affiche pas l'événement, exemple : 
https://www.agenda-menton.fr/agenda/ville-de-menton/brians-group/

**Comment by vincedubroeucq** [comment]
Normalement, c'est réglé.
Le filtre oaq[passed] a été forcé sur les pages événements simples, pour inclure les événements passés.
